apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-tools
spec:
  distribution:
    version: 1.20.9
  topology:
    controlPlane:
      class: best-effort-medium
      count: 1
      storageClass: kubernetes-gold-storage-policy
    workers:
      class: best-effort-medium
      count: 3
      storageClass: kubernetes-gold-storage-policy
  settings:
    storage:
      classes: ["AVI Tanzu vSAN Storage Policy"]              #Named PVC storage classes
      defaultClass: AVI Tanzu vSAN Storage Policy             #Default PVC storage class
