apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-dirk-02
spec:
  distribution:
    version: v1.18
  topology:
    controlPlane:
      class: guaranteed-small
      count: 1
      storageClass: kubernetes-gold-storage-policy
    workers:
      class: guaranteed-small
      count: 0
      storageClass: kubernetes-gold-storage-policy
