apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkc-tools
  namespace:
spec:
  distribution:
    version: v1.22
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-medium
      storageClass: avi-tanzu-vsan-storage-policy
      tkr:  
        reference:
          name: 
    nodePools:
    - name: worker-nodepool-a1
      replicas: 3
      vmClass: best-effort-medium
      storageClass: avi-tanzu-vsan-storage-policy
      tkr:  
        reference:
          name: 
  settings:
    storage:
      classes: ["avi-tanzu-vsan-storage-policy"]              #Named PVC storage classes
      defaultClass: avi-tanzu-vsan-storage-policy             #Default PVC storage class
